In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

Creating DataFrames

In [3]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)

In [4]:
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])

Inspecting Data

In [5]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [8]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

Selecting Data

In [9]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [10]:
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [11]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [12]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

Filtering Data

In [13]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

Adding/Removing Columns

In [14]:
df['Gender'] = ['F', 'M']

In [15]:
df.drop('Age',axis=1,inplace=True)

Handling Missing Data

In [16]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [17]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [18]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

Grouping and Aggregating

In [20]:
df['Age']=[10,9]

In [21]:
df.groupby('Gender')['Age'].mean()

Gender
F    10.0
M     9.0
Name: Age, dtype: float64

Merging & Joining

In [23]:
import pandas as pd

df1 = pd.DataFrame({
    'key': [1, 2, 3],
    'Name': ['A', 'B', 'C']
})

df2 = pd.DataFrame({
    'key': [1, 2, 4],
    'Marks': [90, 85, 95]
})

In [24]:
pd.merge(df1, df2, on='key')

   key Name  Marks
0    1    A     90
1    2    B     85

In [26]:
df1.set_index('key').join(df2.set_index('key'))

    Name  Marks
key
1      A   90.0
2      B   85.0
3      C    NaN

Reading/Writing Files

In [28]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['L', 'E', 'O'],
    'Age': [2, 1, 0]
})

df.to_csv('data.csv', index=False)

In [29]:
df = pd.read_csv('data.csv')

In [30]:
df.to_csv('output.csv', index=False)

Useful Functions

In [31]:
df.sort_values('Age')

  Name  Age
2    O    0
1    E    1
0    L    2

In [32]:
df['Age'].apply(lambda x: x + 1)

0    3
1    2
2    1
Name: Age, dtype: int64

In [33]:
df['Name'].unique()

<StringArray>
['L', 'E', 'O']
Length: 3, dtype: str

In [34]:
df['Age'].value_counts()

Age
2    1
1    1
0    1
Name: count, dtype: int64